send-message:
	nats req svc.onepiece.create-plan '{"title":"Vacation", "color":"#FF0000", "goalAmount":{"amount":"1000", "denomination":"USD"}, "description":"Plan for a vacation", "icon":"https://some-url.com/icon.png", "depositAccountId":"d83a3744-0e53-4fb7-88f7-7ffc831f0090"}'
