send-message:
	nats req srv.command.monitoring.create-monitoring '{\
		"payload": {\
			"CreateMonitoring": {\
				"id": "2",\
				"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"\
			}\
	 	}\
	}'
